- name: Determine if the image exists
  stat:
    path: /var/lib/libvirt/images/{{ image_name }}.qcow2
  register: image_st
- name: Determine if the xml exists
  stat:
    path: /etc/libvirt/qemu/default.xml
  register: default_xml
- name: copy "{{ image_name }}" image
  copy:
    src: "{{ image_name }}.qcow2"
    dest: /var/lib/libvirt/images/{{ image_name }}.qcow2
  when: not image_st.stat.exists
- name: copy default.xml config
  template:
    src: default.xml.j2
    dest: /etc/libvirt/qemu/default.xml 
  when: not default_xml.stat.exists 
